//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventurersGuild.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVENTURER
    {
        public decimal ADVENTURERID { get; set; }
        public decimal PERSONID { get; set; }
        public decimal JOBID { get; set; }
        public string RATING { get; set; }
        public Nullable<System.DateTime> SIGNUP_DATE { get; set; }
        public string STATUS { get; set; }
    
        public virtual JOB JOB { get; set; }
    }
}
