//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventurersGuild.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.JOB = new HashSet<JOB>();
        }
    
        public decimal CLIENTID { get; set; }
        public decimal PERSONID { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> SIGNUP_DATE { get; set; }
        public Nullable<decimal> JOB_COUNT { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOB { get; set; }
    }
}
