//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventurersGuild.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventurersGuildDatabaseEntities : DbContext
    {
        public AdventurersGuildDatabaseEntities()
            : base("name=AdventurersGuildDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADVENTURER> ADVENTURER { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<JOB> JOB { get; set; }
        public virtual DbSet<MONSTER> MONSTER { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
    }
}
