//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventurersGuild.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONSTER
    {
        public decimal MONSTERID { get; set; }
        public decimal JOBID { get; set; }
        public string CHALLANGE_RATING { get; set; }
        public string NAME { get; set; }
        public string WEAKNESSES { get; set; }
        public string RESISTANCES { get; set; }
    
        public virtual JOB JOB { get; set; }
    }
}
